### ISSUE TITLE
At the end of the encrypt, it does not place the contents.json file

### ISSUE THREAD

**Issue by iAldrich23xX** [valaphee/mcrputil#6] opened 2022-12-16 03:45 UTC
Contents.json

**Comment by iAldrich23xX** [comment] 2022-12-16 03:47
At the end of the encrypt, it does not place the contents.json file

**Comment by valaphee** [comment] 2022-12-16 13:28
Which command line arguments do you use, and whats your console output?

**Comment by iAldrich23xX** [comment] 2022-12-16 14:06
> Which command line arguments do you use, and whats your console output?
![image](https://user-images.githubusercontent.com/39071289/208115207-d3708aa0-ec2f-45a0-9521-8dbc502965b7.png)

![image](https://user-images.githubusercontent.com/39071289/208115300-1b9a95fd-66d5-4258-894c-0d4f3b94eb4e.png)


"Error : key must be a string at line 659 column 8"

**Comment by valaphee** [comment] 2022-12-17 02:50
Heya, this error is caused by a malformed json file, but malformed json files should now be added anyway.

Should be fixed with version 1.1.2

**Closed** 2022-12-18 16:06 UTC
